mutation CreateOneUser($data: UserCreateInput!) {
  createOneUser(data: $data) {
    ...UserInfo
  }
}

mutation CreateOnePost($data: PostCreateInput!) {
  createOnePost(data: $data) {
    ...PostInfo
  }
}
